import type { Metadata } from "next";
import { MuseoModerno } from "next/font/google";
import "./globals.css";

const museo = MuseoModerno({ subsets: ["latin"], display: 'swap', variable: '--font-musero-moderno' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={museo.className}>{children}</body>
    </html>
  );
}
